Repository kartoza/geocontext, pull requests merged in 2018-07, with the labels that each got.

#13 Fix wrong version and source url in geocontext.json.
  django_project/base/management/commands/geocontext.json
  django_project/geocontext/migrations/0014_auto_20180716_0624.py
  django_project/geocontext/models/context_cache.py
  django_project/geocontext/models/context_service_registry.py
Labels: review

#15 Update landing page.
  django_project/base/templates/landing_page.html
  django_project/core/base_static/libs/font-awesome/css/font-awesome.css
  django_project/core/base_static/libs/font-awesome/css/font-awesome.css.map
  django_project/core/base_static/libs/font-awesome/css/font-awesome.min.css
  django_project/core/base_templates/main_base.html
Labels: in progress, review

#16 Add notes, licensing, and provenance to CSR.
  django_project/base/management/commands/geocontext.json
  django_project/geocontext/migrations/0015_auto_20180717_0333.py
  django_project/geocontext/models/context_service_registry.py
  django_project/geocontext/serializers/context_service_registry.py
Labels: in progress, review

#19 Add api docs and tidy up docs.
  django_project/base/urls.py
  django_project/core/base_templates/main_base.html
  django_project/geocontext/views/api.py
Labels: in progress, in review, review

#24 Add unit test for testing the data from geocontext.json.
  django_project/core/settings/base.py
  django_project/geocontext/tests/test_import_real_data.py
Labels: in progress, in review, review

#23 Added new layer configurations
  django_project/base/management/commands/geocontext.json
Labels: in progress, in review, review
